### ISSUE TITLE
bug: pip install does not work anymore

### ISSUE THREAD

**Issue by clatze** [abhishek-ram/pyas2#14]
Downloading/unpacking pyas2
  Downloading pyAS2-0.2.tar.gz (247kB): 247kB downloaded
  Running setup.py (path:/tmp/pip-build-KEI3C8/pyas2/setup.py) egg_info for package pyas2
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-KEI3C8/pyas2/setup.py", line 4, in <module>
        with open(os.path.join(os.path.dirname(**file**), 'pyAS2/README.rst')) as readme:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-KEI3C8/pyas2/pyAS2/README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-KEI3C8/pyas2/setup.py", line 4, in <module>

```
with open(os.path.join(os.path.dirname(__file__), 'pyAS2/README.rst')) as readme:
```

IOError: [Errno 2] No such file or directory: '/tmp/pip-build-KEI3C8/pyas2/pyAS2/README.rst'

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-KEI3C8/pyas2
Storing debug log for failure in /home/latze/.pip/pip.log

**Comment by abhishek-ram** [comment]
Fixed follow this process for upgrading-
http://pyas2.readthedocs.org/en/stable/installation.html#upgrading-pyas2
