### ISSUE TITLE
Payload not viewable after signature verification error

### ISSUE THREAD

**Issue by kurohai** [abhishek-ram/pyas2#16]
When receiving a message from a partner I get an error: Signature Verification Failed, exception message is certificate verify error.

I can see the MDN I sent back, but the original incoming message isn't saved to a file, and isn't viewable in messages page.

**Comment by abhishek-ram** [comment]
Saving of the message is the last step in the process and is done only after it passes all the verification. I f you still want to see the message you should turn on debugging and the message will be shown in the logs.

**Comment by kurohai** [comment]
The use of debugging should be a stop-gap.

Seeing what is in the message is helpful to troubleshooting certificate problems. A simple certification mismatch shouldn't require debugging. There isn't anything in the application that needs debugging at that point. It's a configuration error.

**Comment by abhishek-ram** [comment]
Well the message is saved by the system only after it passes all the checks, this is how its always done. And debugging here is meant exactly for the purpose you described (i.e. for use of testing the connection at the time of on-boarding). Consider for example the debugging modes used in BOTS for troubleshooting mapping and other scripts.
