### ISSUE TITLE
UI is not the same as the one from the documentation

### ISSUE THREAD

**Issue by fredy2015** [abhishek-ram/pyas2#17]
Hi,

I have followed the installation instructions from the doc. But when I access to the UI, I dont have the same as the one in the doc. I don't have the logo, name of the server, all the tabs (run, etc...). I have only the "pyAS2 Global Settings" and a tab Home which redirect to the Django admin page...

My server is on Linux Fedora 23 Server. Python version is 2.7.10 and the Django version is 1.9.3.

Could you help & advise.
Thanks

Fred

**Comment by abhishek-ram** [comment]
`pyas2` needs to be placed at top of the list of `INSTALLED_APPS` in `settings.py`
I will update the documentation to reflect the same.
Also there are some issues with the newer version of Django and I will push in a change to take care of these errors.

**Comment by fredy2015** [comment]
It works!

Thanks
