### ISSUE TITLE
call_command instead of subprocess.Popen

### ISSUE THREAD

**Issue by lovegandhi** [abhishek-ram/pyas2#28]
Django provides a builtin function for calling commands `django.core.management.call_command`
Is there something that Popen is providing in this case that call_command does not? Looking to see if I am missing something obvious.

```
python_executable_path = pyas2init.gsettings['python_path']
managepy_path = pyas2init.gsettings['managepy_path']
...
lijst = [
    python_executable_path,
    managepy_path,
    'sendas2message',
    '--delete',
    form.cleaned_data['organization'],
    form.cleaned_data['partner'],
    temp.name
]
subprocess.Popen(lijst).pid
```

Can be simplified by using:

```
kwargs = {
    'delete': delete,
    'organization_as2name': form.cleaned_data['organization'],
    'partner_as2name': form.cleaned_data['partner'],
    'path_to_payload': temp.name
}
call_command('sendas2message', **kwargs)
```

**Comment by abhishek-ram** [comment]
Yes you are right we can use the call_command. I had not used this as I was not aware of its existence. If you have the time and the inclination then please make the relevant changes and open a PR.
