### ISSUE TITLE
error while inbound

### ISSUE THREAD

**Issue by rootstat** [abhishek-ram/pyas2#35]
-

**Comment by abhishek-ram** [comment]
You generally see this error if the certificate fails to pass the openssl verification. One way to resolve this is to disable verification for this certificate (Use the checkbox)

**Comment by rootstat** [comment]
where could i see this checkbox ?

**Comment by rootstat** [comment]
-

**Comment by rootstat** [comment]
-

**Comment by rootstat** [comment]
abhishek, i'm stucked on this error for past 3 days.

**Comment by abhishek-ram** [comment]
Yeah its in the public certificates section, just edit that certificate and you will find this option

**Comment by rootstat** [comment]
-

**Comment by rootstat** [comment]
-
