### ISSUE TITLE
Problem installing pyAS2 on Windows 2012

### ISSUE THREAD

**Issue by iversa** [abhishek-ram/pyas2#41]
I'm trying to install pyAS2 on Windows 2012 server. This is how far I get

    SWIG/_m2crypto_wrap.c(3541) : fatal error C1083: Cannot open include file: '
openssl/err.h': No such file or directory
    error: command 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Common\\
Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status
2

**Comment by abhishek-ram** [comment]
The issue is with M2Crypto installation, please go through this file https://gitlab.com/m2crypto/m2crypto/blob/master/INSTALL.rst#id4 and install it seperately. Then run the pyAS2 installation.
