### ISSUE TITLE
Any plans to support SHA-2?

### ISSUE THREAD

**Issue by stetskevych** [abhishek-ram/pyas2#42]
I'm considering trying out pyAS2, but SHA-2 (or SHA256) is not mentioned in the supported list.

**Comment by manassehkatz** [comment]
I need SHA-2 for one of my customer's vendors. It looks like the only references to actually using sha1 are via hashlib (3 lines in pyas2lib.py). If that's really all there is to it, then it should be very simple to add SHA-2 as hashlib has supported it for a long time.

**Comment by abhishek-ram** [comment]
The thing is that pyAS2 already supports SHA-2 when validating signatures, however when generating a signature the underlying Openssl functions decide the algorithm based on various conditions. I am not really sure how it is deciding which algorithm to use but we do not have the choice to specify it so this cannot be supported directly at the moment

**Comment by manassehkatz** [comment]
I'll have to experiment a bit and see what I can figure out. Is there any publicly available target test system, besides just setting up 2 pyAS2 systems locally (which is what the previous programmer on my project did)?

**Comment by abhishek-ram** [comment]
No there is no public test system.

**Comment by activeyossi** [comment]
Just finished installing this repo, awesome work man!
But this SHA coding seems to be a problem when trying to configure a test connection with VendorCentral.
Have you ever been able to figure this out? 
Looks like many vendors require SHA-256 and even SHA-512
