### ISSUE TITLE
Setting up pyAS2 on Ubuntu

### ISSUE THREAD

**Issue by iversa** [abhishek-ram/pyas2#45]
Since I can't get it to work on Windows I figure I try on Ubuntu. I'm a newby to Linux to bear with me.

I have everything setup up until I need to run the following

`python manage.py migrate`

I get 

`python: can't open file 'manage.py': [Errno 2] No such file or directory`

Does not help either when I change the path to /usr/local/lib/python2.7/dist-packages/django or /usr/local/lib/python2.7/dist-packages/pyas2

**Comment by keegandsouza** [comment]
You aren't running the migrate command in the right directory. You need to run it in the same directory where your manage.py file is located. If you followed the installation guide in the docs then you need to navigate to the project dir. Run the below command in whichever directory to ran the installation instructions
`cd django_pyas2/`
