### ISSUE TITLE
Hashing algorithms other than sha-1

### ISSUE THREAD

**Issue by vpontis** [abhishek-ram/pyas2#47]
Hi there, is anyone working on or planning to work on sha-256 or sha-512 hashing? I am looking at integrating with a partner who does not accept sha-1.

I would be willing to help if someone is starting on this project or I could work on it if someone can give me advice :)

**Comment by abhishek-ram** [comment]
@vpontis  the issue here is that the current lib depends on M2Crypto and this does not allow choosing the hashing algo. I am currently working on another repo https://github.com/abhishek-ram/django-pyas2 that moves away from M2Crypto and is able to provide this function. I am almost done with this but just got busy lately, it will take about 2 to 3 weeks to complete this.

**Comment by vpontis** [comment]
Ah awesome. Looks cool. 


What are you building this as2 server for? What is your use case?

—
Victor Pontis

--- original message ---
> Fri, Mar 9 at 17:53, <notifications@github.com> wrote:


> @vpontis the issue here is that the current lib depends on M2Crypto and this does not allow choosing the hashing algo. I am currently working on another repo https://github.com/abhishek-ram/django-pyas2 that moves away from M2Crypto and is able to provide this function. I am almost done with this but just got busy lately, it will take about 2 to 3 weeks to complete this.

> —

> You are receiving this because you were mentioned.

> Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by abhishek-ram** [comment]
I do EDI integrations for my clients and I use it for this.

**Comment by Gnurpreet** [comment]
Hi,
+1 for this request.

We installed pyas2 on our servers to realize that sha-256 is not supported. Can I help to expedite it someway?

**Comment by abhishek-ram** [comment]
@Gnurpreet been real busy lately but i will have time in the coming weeks so I plan to do the first release this month.

**Comment by Gnurpreet** [comment]
@abhishek-ram if you guide us in the right direction, me and my team could look at implementing this. Else, if some commercial help could accelerate?

**Comment by abhishek-ram** [comment]
I am actually about to do a beta release and would love your help with testing, bug-fixing and improvements. I will let you know as soon as its out.

**Comment by landreville** [comment]
I'm also interested in SHA-256 support. My use-case is implementing Canadian phone number porting regulations that require an AS2 server with SHA-256 support (if you really want to be bored, the data interchange spec is here https://crtc.gc.ca/public/cisc/bp/BPGLDI32.doc).

**Comment by abhishek-ram** [comment]
@vpontis @Gnurpreet @landreville  The beta version of the new lib is now available. Please help in testing this and raise any issues here https://github.com/abhishek-ram/django-pyas2
